version: "3.9"

services:

  app:
    build: .
    container_name: school_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: school_management
      DB_USERNAME: render
      DB_PASSWORD: secret

  db:
    image: postgres:16
    container_name: school_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: school_management
      POSTGRES_USER: render
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U render -d school_management"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: